Fix stack organization
rapid7/mettle pull request #268
Opened 2024-11-01 18:09 UTC by rafajunio

Wrong calculation in the near the limits of argv, envv and auxv

2024-12-05 15:11 UTC, dledda-r7 reviewed
Hello! Thanks for your PR.
I am leaving couple of questions to get a bit of context for these changes.

2025-01-30 00:29 UTC, acammack requested changes
Ah yes, off-by-one errors, the bane of long nights and blurry debugger sessions. This one is made even worse by the debug output looking correct as it mangles the stack it's trying to produce and that stack mostly working :smiling_imp: . Thanks for the catch, cheers!

2025-01-30 00:29 UTC, acammack commented on libreflect/src/stack_setup.c
> +		stack_base[2 + argc + ii] = (size_t)env[ii];
For clarity of what's going on (and to hopefully discourage other off-by-one-errors, I would recommend:
```suggestion
		stack_base[1+ argc + ii + 1] = (size_t)env[ii];
```

2025-01-30 00:29 UTC, acammack commented on libreflect/src/stack_setup.c
> +		dprint("  0x%08zx\n", stack_base[2 + argc + ii]);
As above
```suggestion
		dprint("  0x%08zx\n", stack_base[1 + argc + ii + 1]);
```

2025-01-30 00:29 UTC, acammack commented on libreflect/src/stack_setup.c
> +	stack_base[3 + argc + ii] = 0;
Speaking of off-by-one errors this needs to be in line with the environment vector  ;). As above, to make that clear I would format it as:
```suggestion
	stack_base[1 + argc + ii +1] = 0;
```

2025-01-30 00:29 UTC, acammack commented on libreflect/src/stack_setup.c
> +	dprint("  0x%08zx\n", stack_base[3 + argc + ii]);
And again:
```suggestion
	dprint("  0x%08zx\n", stack_base[1 + argc + ii + 1]);
```

2025-01-30 00:29 UTC, acammack commented on libreflect/src/stack_setup.c
> +	auxv_base = stack_base + 1 + argc + ii + 3;
And here,  it's just 3 total (argc plus two nulls), formatted to make that clear:
```suggestion
	auxv_base = stack_base + 1 + argc + ii + 1 + 1;
```

2025-01-30 00:29 UTC, acammack commented on libreflect/src/stack_setup.c
> +		for (ii = 0; auxv[ii] || auxv[ii + 1]; ii++) {
The auxiliary vector terminated solely by `AT_NULL`, it's value is not specified in the ABI. To be safe, this should increment by two and copy off in pairs, similar to how `AT_NULL` is set below:
```suggestion
		for (ii = 0; auxv[ii]; ii += 2) {
 			auxv_base[ii] = auxv[ii];
 			auxv_base[ii + 1] = auxv[ii + 1];
```

2025-01-30 00:29 UTC, acammack commented on libreflect/src/stack_setup.c
> +	for (ii = 0; auxv[ii] || auxv[ii + 1]; ii += 2) {
Since it's just `AT_NULL` signalling the end of the vector, this change does not make sense
```suggestion
	for (ii = 0; auxv[ii]; ii += 2) {
```

2025-02-01 21:53 UTC, acammack reviewed
Thanks, the code tests correctly and looks good to me! As a heads up, Rapid7 usually requires PRs to be made from unique topic branches, though I'll let the current team members take it from here

2025-02-27 15:19 UTC, adfoster-r7 commented
@rafajunio It'd be great to rebase this PR, we had to make some changes for CI to run: https://github.com/rapid7/mettle/pull/272

2025-02-27 20:42 UTC, rafajunio commented
Lesson learned, not use master to create PR anymore =) (my fork)

Thank you, I hope that now is everything good. I merge the commits in the rebase as well.

2025-09-13 16:40 UTC, rafajunio commented
Hello, did you guys want any change in this PR? Change the description? change the branch? reopen in another format? whatever you guys want. The changes are simple.

2025-09-17 16:22 UTC, smcintyre-r7 approved these changes
With the test code, I was able to confirm the original bug and then validate the fix. Thanks for your patience as we reviewed and tested this.

<details>
<summary>Old and broken</summary>

```
build/x86_64-linux-musl/libreflect/examples/noexec print_stack this is a test
argc: 5

argv[0]: print_stack
argv[1]: this
argv[2]: is
argv[3]: a
argv[4]: test
argv[5]: RUBY_VERSION=ruby-3.0.4
argv[6]: GNOME_SETUP_DISPLAY=:1
...
```
</details>

<details>
<summary>New and fixed</summary>

```
build/x86_64-linux-musl/libreflect/examples/noexec print_stack this is a test
argc: 5

argv[0]: print_stack
argv[1]: this
argv[2]: is
argv[3]: a
argv[4]: test

envv[0]: RUBY_VERSION=ruby-3.0.4
envv[1]: GNOME_SETUP_DISPLAY=:1
...
</details>

2025-09-17 16:22 UTC, merged